# Generated by Django 5.1.6 on 2025-03-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alert'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alert',
            table=None,
        ),
    ]
