# Generated by Django 5.1.6 on 2025-03-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_alert_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alert',
            table='alert',
        ),
    ]
