# Generated by Django 5.1.6 on 2025-03-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_alert_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='destination',
            new_name='attacker',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='id',
            new_name='rule_id',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='source',
            new_name='target_ip',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='computer',
            new_name='target_name',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='account_name',
        ),
        migrations.AddField(
            model_name='alert',
            name='incident_response_desc',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('resolved', 'resolved'), ('error', 'error')], default='pending', max_length=8),
            preserve_default=False,
        ),
    ]
