# Generated by Django 5.1.6 on 2025-03-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_description_alert_incident_response_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='Incident_Response_Desc',
            field=models.TextField(db_column='Incident_Response_Desc'),
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='Incident_Response_Desc',
            new_name='incident_response_desc',
        ),
    ]
