# Generated by Django 5.1.6 on 2025-03-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_alert_incident_response_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='description',
            new_name='alert_desc',
        ),
    ]
